### ISSUE TITLE
@Local causes weird log spam when used a a specific way

### ISSUE THREAD

**Issue by IThundxr** [LlamaLad7/MixinExtras#58]
Log: https://mclo.gs/LcRO1u3

Class: https://github.com/Layers-of-Railways/Railway/blob/e40ef63f1a723f3dd48045991b51f5b3b8cadb98/common/src/main/java/com/railwayteam/railways/mixin/MixinTrackPlacement.java

That exact class's @Local somehow causes mixin/mixin extras to complain about it, as soon as i comment that mixin out theres no errors, not sure whats exactly going on so any help would be appreciated, (or it being fixed if it isnt a fault on my side)

**Comment by LlamaLad7** [comment]
This is an issue with Mixin itself simply caused by a missing null check [here](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/util/asm/MixinVerifier.java#L104). The same logspam occurs when using ordinary local capture in an `@Inject`. I'd suggest opening an issue there and on FabricMC/Mixin. I'll try to make a PR to the latter when I have time.
